name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libpoco-dev libelf-dev libdwarf-dev
        version: 1.0
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: make
      run: cd build && make
    - name: make test
      run: cd build && make test
