name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libpoco-dev libelf-dev libdwarf-dev libspdlog-dev ninja-build
        version: 1.0
    - name: configure
      run: mkdir build && cd build && cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ..
    - name: build
      run: cd build && ninja
    - name: test
      run: cd build && ninja test
    - name: release-build
      run: cd build && cmake -G Ninja -DCMAKE_BUILD_TYPE=Release .. && ninja
    - name: package
      run: cd build && cpack
    - uses: actions/upload-artifact@v2
      with:
        name: deb
        path: build/*.deb
