name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libpoco-dev libelf-dev libdwarf-dev libspdlog-dev ninja-build libbackward-cpp-dev
        version: 1.0
    - name: configure
      run: mkdir build-debug && cd build-debug && cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DENABLE_USER_LIST=On -DENABLE_SIGNUP=On ..
    - name: build-debug
      run: cd build-debug && ninja
    - name: test
      run: cd build-debug && ninja test
    - name: build-release
      run: ./scripts/create-release.sh
    - uses: actions/upload-artifact@v4
      with:
        name: cpp_webserver_kata-0.1.1-Linux.deb
        path: build-release/*.deb
